### ISSUE TITLE
Not compatible with django 1.9 since django.contrib.contenttypes.generic is remove in django 1.9

### ISSUE THREAD

**Issue by elfxiong** [dominno/django-moderation#146]
Trying to ```migrate``` or ```runserver``` gives ```cannot import generic``` error.
Then I saw in [django's 1.9 release note](https://docs.djangoproject.com/en/1.9/releases/1.9/) that they have removed ```django.contrib.contenttypes.generic```.

I tried to replace 
```
from django.contrib.contenttypes import generic
```
with
```
from django.contrib.contenttypes.fields import GenericForeignKey
```
and change ```generic.GenericForeignKey``` to ```GenericForeignKey``` accordingly.

But it gives me another error, which I have no idea about:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/site-packages/moderation/__init__.py", line 1, in <module>
    from moderation.register import ModerationManager
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/site-packages/moderation/register.py", line 3, in <module>
    from moderation.models import ModeratedObject, MODERATION_STATUS_PENDING,\
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/site-packages/moderation/models.py", line 3, in <module>
    from django.contrib.contenttypes import fields as generic
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/site-packages/django/contrib/contenttypes/fields.py", line 5, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/site-packages/django/contrib/contenttypes/models.py", line 159, in <module>
    class ContentType(models.Model):
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/xq/Repositories/myapp/venv/lib/python3.5/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by elfxiong** [comment]
Never mind. I just downloaded this whole github repo and used it and it worked. Everything has been fixed but the problem is that the latest release of django-moderation was in 2014. Can anyone make a release?
