### ISSUE TITLE
After installation pip3 install django-moderation

### ISSUE THREAD

**Issue by Allan-Nava** [dominno/django-moderation#160]
I got this error:

> Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f82ab355488>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 228, in wrapper
>     fn(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run
>     autoreload.raise_last_exception()
>   File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 251, in raise_last_exception
>     six.reraise(*_exception)
>   File "/usr/local/lib/python3.5/dist-packages/django/utils/six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 228, in wrapper
>     fn(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 27, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 116, in populate
>     app_config.ready()
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/admin/apps.py", line 23, in ready
>     self.module.autodiscover()
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
>     autodiscover_modules('admin', register_to=site)
>   File "/usr/local/lib/python3.5/dist-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
>     import_module('%s.%s' % (app_config.name, module_to_search))
>   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "/usr/local/lib/python3.5/dist-packages/moderation/admin.py", line 25, in <module>
>     from .helpers import automoderate
>   File "/usr/local/lib/python3.5/dist-packages/moderation/helpers.py", line 3, in <module>
>     from .register import RegistrationError
>   File "/usr/local/lib/python3.5/dist-packages/moderation/register.py", line 13, in <module>
>     from .moderator import GenericModerator
>   File "/usr/local/lib/python3.5/dist-packages/moderation/moderator.py", line 3, in <module>
>     from django.contrib.sites.models import Site
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sites/models.py", line 84, in <module>
>     class Site(models.Model):
>   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 118, in __new__
>     "INSTALLED_APPS." % (module, name)
> RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

This is my settings.py

# Application definition
```
INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.admindocs',
   # 'django.contrib.auth',
   # 'django.contrib.contenttypes',
   # 'django.contrib.sessions',
#    'django.contrib.sites',
   # 'django.contrib.messages',
    #'django.contrib.staticfiles',
 #   'django.contrib.flatpages',
    'bootcamp.allejo',
    'bossoidc',
    'djangooidc',
#    'djangocms_oscar',
    'bootstrap3',
    'guardian',
    'bootcamp.groups_manager',
    'bootcamp.activities',
    'bootcamp.articles',
    'bootcamp.authentication',
    'bootcamp.core',
    'bootcamp.feeds',
    'bootcamp.messenger',
    'bootcamp.questions',
    'bootcamp.search',
    'rest_framework',
    'rest_framework_swagger',
    'taggit',
    'moderation',
    #'djpikaday',
    #'permission',
    #'bootcamp.parents'
)
```

![screen shot 2017-11-30 at 17 47 32](https://user-images.githubusercontent.com/22498435/33443001-be6a8956-d5f6-11e7-8a9a-aa4265c3398d.png)

**Comment by Allan-Nava** [comment]
Django moderation supported python3??

**Comment by Allan-Nava** [comment]
I have fixed added in INSTALLED_APPS =>` 'django.contrib.sites',`
