### ISSUE TITLE
autodiscovery fails when using AppConfig install

### ISSUE THREAD

**Issue by tlambert03** [dominno/django-moderation#162]
i'm new to django-moderation and somewhat new to django as well, so I apologize if I'm overlooking something basic.  I've been unable to add `'moderation.apps.ModerationConfig'` to `INSTALLED_APPS` – even with a fresh `django startproject` (django 1.11.9) – due to what seems to be an incompatibility with the way `helpers.auto_discover` pulls directly from `settings.INSTALLED_APPS`... I get the error:
```
ModuleNotFoundError: No module named 'moderation.apps.ModerationConfig'; 'moderation.apps' is not a package
```
(and I get the same error with all of my custom apps that are installed using appConfig paths instead of package names).  This makes sense of course, since `helpers.import_moderator()` can't use `import_module()` to directly import the AppConfig class itself.  The only way I can get it to work is by changing the auto_discover function to use `get_app_configs()`:
```python
def auto_discover():
    from django.apps import apps
    for app in [app.name for app in apps.get_app_configs() if app != 'moderation']:
        import_moderator(app)
```

However, using `'moderation.apps.ModerationConfig'` as the install string is described in the docs, so I feel I must be in error somehow?

**Comment by zypro** [comment]
The install string in the docs is **'moderation.apps.SimpleModerationConfig'** insead of ModerationConfig!! That's the important difference.

**Comment by LennyLip** [comment]
@zypro thanks, I had the same issue, but there are https://django-moderation.readthedocs.io/en/latest/getting_started.html#installation ModerationConfig in the docs.

**Comment by tlawren3** [comment]
I'm experiencing this issue in a similar manner.

relevant section of installed_apps:
    'moderation',
    'users.apps.UsersConfig',
    'core',

when I insert moderation into my installed_apps and attempt to migrate, I get this error:

 File "/Users/tlawrence/.conda/envs/hiccup/lib/python3.7/site-packages/moderation/apps.py", line 13, in ready
    auto_discover()
  File "/Users/tlawrence/.conda/envs/hiccup/lib/python3.7/site-packages/moderation/helpers.py", line 48, in auto_discover
    import_moderator(app)
  File "/Users/tlawrence/.conda/envs/hiccup/lib/python3.7/site-packages/moderation/helpers.py", line 27, in import_moderator
    app_path = import_module(app).__path__
  File "/Users/tlawrence/.conda/envs/hiccup/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.apps.UsersConfig'; 'users.apps' is not a package

I confirmed that it works if I remove moderation from my installed apps. Please advise.

**Comment by DmytroLitvinov** [comment]
Please reopen issue it still exists in new version(0.7) of `django-moderation`

**Comment by MaybeThisIsRu** [comment]
I'm facing this issue as well on `django-moderation@0.8` with Django 3.2:

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/ruhi/.asdf/installs/python/3.9.6/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/ruhi/.asdf/installs/python/3.9.6/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ruhi/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/ruhi/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/Users/ruhi/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/ruhi/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/ruhi/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/ruhi/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/ruhi/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/Users/ruhi/.local/share/virtualenvs/do-4FLlvcb7/src/django-moderation/moderation/apps.py", line 15, in ready
    auto_discover()
  File "/Users/ruhi/.local/share/virtualenvs/do-4FLlvcb7/src/django-moderation/moderation/helpers.py", line 48, in auto_discover
    import_moderator(app)
  File "/Users/ruhi/.local/share/virtualenvs/do-4FLlvcb7/src/django-moderation/moderation/helpers.py", line 27, in import_moderator
    app_path = import_module(app).__path__
  File "/Users/ruhi/.asdf/installs/python/3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 981, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rules.apps.AutodiscoverRulesConfig'; 'rules.apps' is not a package
```

I looked at a similar package and they make use of some Django built-ins to achieve auto discovery for `rules.py`:

https://github.com/dfunckt/django-rules/blob/master/rules/apps.py#L12-L15

Would it be possible to do something like this for `moderation.py` with this package?

**Comment by MaybeThisIsRu** [comment]
I'm facing this issue as well on `django-moderation@0.8` with Django 3.2:

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/djangouser/.asdf/installs/python/3.9.6/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/djangouser/.asdf/installs/python/3.9.6/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/djangouser/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/djangouser/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/Users/djangouser/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/djangouser/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/djangouser/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/djangouser/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/djangouser/.local/share/virtualenvs/do-4FLlvcb7/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/Users/djangouser/.local/share/virtualenvs/do-4FLlvcb7/src/django-moderation/moderation/apps.py", line 15, in ready
    auto_discover()
  File "/Users/djangouser/.local/share/virtualenvs/do-4FLlvcb7/src/django-moderation/moderation/helpers.py", line 48, in auto_discover
    import_moderator(app)
  File "/Users/djangouser/.local/share/virtualenvs/do-4FLlvcb7/src/django-moderation/moderation/helpers.py", line 27, in import_moderator
    app_path = import_module(app).__path__
  File "/Users/djangouser/.asdf/installs/python/3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 981, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rules.apps.AutodiscoverRulesConfig'; 'rules.apps' is not a package
```

I looked at a similar package and they make use of some Django built-ins to achieve auto discovery for `rules.py`:

https://github.com/dfunckt/django-rules/blob/master/rules/apps.py#L12-L15

Would it be possible to do something like this for `moderation.py` with this package?

**Comment by MaybeThisIsRu** [comment]
It looks like auto discovery in `django-moderation` tries to import even 3rd party packages, and only excludes itself if installed as `moderation` and not as `moderation.apps.ModerationConfig` due to [the hard coded string here](https://github.com/dominno/django-moderation/blob/v0.8.0/moderation/helpers.py#L47).

So we should either

1. update code to also include `moderation.apps.ModerationConfig`
2. or update docs to only say `moderation` when adding to `INSTALLED_APPS`

**Comment by MaybeThisIsRu** [comment]
I have a working example on my branch: https://github.com/MaybeThisIsRu/django-moderation/commits/fix-autodiscovery

**Comment by DmytroLitvinov** [comment]
Hi @MaybeThisIsRu ,
Thank you for providing more info about it.
Yes, we can fix it. PRs are welcome to it
